package abc.music.editor.help;

import abc.music.editor.AbcMusicEditor;
import abc.music.editor.AmeConstants;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import se.digitman.lightxml.DocumentToXmlNodeParser;
import se.digitman.lightxml.XmlNode;

/**
 *
 * @author hl
 */
public class HelpDialog extends JDialog {

    private final Dimension dialogDimension = new Dimension(1000, 700);

    public HelpDialog(AbcMusicEditor parent) {
        super(parent, "Hex ABC Music Editor - Help", true);
        initComponents();
        super.setSize(dialogDimension);
        super.setPreferredSize(dialogDimension);

        setupMenu();

        super.setLocationRelativeTo(parent);
    }

    @Override
    protected JRootPane createRootPane() {
        JRootPane customRootPane = new JRootPane();
        ActionListener escActionListener = (ActionEvent e) -> {
            setVisible(false);
        };
        customRootPane.registerKeyboardAction(escActionListener,
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
        return customRootPane;
    }
    
    void setContent(String content) {
        contentLabel.setText(content);
    }

    private void setupMenu() {
        InputStream stream = HelpDialog.class.getResourceAsStream("/help/help.xml");
        XmlNode helpNode = new DocumentToXmlNodeParser(stream).parse();
        for (XmlNode childNode : helpNode.getChildren()) {
            if (!childNode.isCdata()) {
                String nodeName = childNode.getName();
                switch (nodeName) {
                    case "item-group":
                        menuPanel.add(new HelpMenuGroup(this, childNode));
                        break;
                    case "item":
                        menuPanel.add(new HelpMenuItem(this, childNode));
                        break;
                }
            }
        }
        menuPanel.repaint();
        menuPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        contentLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        menuPanel.setBackground(AmeConstants.HELP_DIALOG_BACKGOUND_COLOR);
        menuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 12, 18, 12));
        menuPanel.setLayout(new javax.swing.BoxLayout(menuPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(menuPanel);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel2.setBackground(AmeConstants.HELP_DIALOG_BACKGOUND_COLOR);
        jPanel2.setLayout(new java.awt.BorderLayout());

        headerLabel.setFont(AmeConstants.BIG_TITLE_FONT);
        headerLabel.setForeground(AmeConstants.TITLE_COLOR);
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Hex ABC Music Editor");
        jPanel2.add(headerLabel, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setOpaque(false);

        jPanel1.setBackground(AmeConstants.HELP_DIALOG_BACKGOUND_COLOR);
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        contentLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contentLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(contentLabel);

        jScrollPane3.setViewportView(jPanel1);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contentLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
