package abc.music.editor.components;

import abc.music.core.domain.Project;
import abc.music.core.domain.Voice;
import java.util.List;
import abc.music.editor.AbcMusicEditor;

/**
 *
 * @author hl
 */
public class VoicesPanel extends AmePanel {

    public VoicesPanel(AbcMusicEditor parent, Project project) {
        super(parent, project, "Voices");
    }

    @Override
    protected void init() {
        initComponents();
    }

    public void clearVoices() {
        voicesTabbedPane.removeAll();
        voicesTabbedPane.repaint();
        voicesTabbedPane.revalidate();
        getParent().repaint();
        getParent().revalidate();
        super.repaint();
        super.revalidate();
    }

    public void setVoices(List<Voice> voices) {
        clearVoices();
        voices.stream().forEach(this::addVoice);
    }

    public void addVoice(Voice voice) {
        if (voice != null) {
            voicesTabbedPane.add(voice.getName(), new VoicePanel(editor, project, voice));
            repaint();
            revalidate();
            voicesTabbedPane.repaint();
            voicesTabbedPane.revalidate();
        }
    }

    public void updateVoices() {
        for (int i = 0; i < voicesTabbedPane.getComponentCount(); i++) {
            if (voicesTabbedPane.getComponent(i) instanceof VoicePanel) {
                ((VoicePanel) voicesTabbedPane.getComponent(i)).updateVoice();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voicesTabbedPane = new javax.swing.JTabbedPane();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        voicesTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        add(voicesTabbedPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane voicesTabbedPane;
    // End of variables declaration//GEN-END:variables
}
