package abc.music.editor.gui.dialog;

import abc.music.core.domain.FormatTemplate;
import abc.music.core.domain.PostScriptFont;
import abc.music.editor.AbcMusicEditor;
import abc.music.editor.action.ShowPostScriptFontsAction;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author hl
 */
public class FormatTemplateDialog extends AmeDialog {

    private FormatTemplate template;
    private List<FontPanel> fontPanels;

    public FormatTemplateDialog(AbcMusicEditor editor) {
        super(editor, "Format Template Editor");
    }

    @Override
    protected void init() {
        initComponents();
        initFields();
    }

    public void setFormatTemplate(FormatTemplate template) {
        this.template = template;
        updateFields();
    }

    private void updateFields() {
        if (template != null) {
            templateNameTextField.setText(template.getName());
            shortDescriptionTextArea.setText(template.getShortDescription());
            if (template.hasIndent()) {
                indentTextField.setText(template.getIndent().toString());
            }
            if (template.hasScale()) {
                scaleTextField.setText(template.getScale().toString());
            }
            if (template.hasMaxSrhinking()) {
                maxShrinkingTextField.setText(template.getMaxShrinking().toString());
            }
            if (template.hasStretchLastStaff()) {
                stretchLastStaffCheckBox.setSelected(template.getStretchLastStaff().equals(Boolean.TRUE));
            }
            if (template.hasLandscape()) {
                landscapeCheckBox.setSelected(template.getLandscape().equals(Boolean.TRUE));
            }
            if (template.hasBarsPerStaff()) {
                barsPerStaffTextField.setText(template.getBarsPerStaff().toString());
            }
        }
    }

    private void initFields() {
        initSpacesPanel();
        fontPanels = new ArrayList<>();
        List<FormatTemplate.Font> fonts = new ArrayList<>();
        fonts.addAll(FormatTemplate.getTitleFonts());
        fonts.addAll(FormatTemplate.getTextFonts());
        initFontsPanel(tntFontsPanel, fonts, true);
        initFontsPanel(otherFontsPanel, FormatTemplate.getOtherFonts(), false);
    }

    private void initFontsPanel(JPanel fontsPanel, List<FormatTemplate.Font> fonts, boolean setAll) {
        GridLayout layout = (GridLayout) fontsPanel.getLayout();
        int cells = layout.getRows() * layout.getColumns();
        fonts.stream().forEach((font) -> {
            FontPanel panel = new FontPanel(font);
            fontsPanel.add(panel);
            fontPanels.add(panel);
        });
        int cellIndex = fontsPanel.getComponentCount();
        while (cellIndex < cells - 1) {
            fontsPanel.add(new JLabel());
            cellIndex++;
        }
        if (setAll) {
            FontPanel allFontsPanel = new FontPanel(null);
            fontsPanel.add(allFontsPanel);
        } else {
            fontsPanel.add(new JLabel());
        }
    }

    private void initSpacesPanel() {
        GridLayout layout = (GridLayout) spacesPanel.getLayout();
        int cells = layout.getRows() * layout.getColumns();
        for (FormatTemplate.Space space : FormatTemplate.Space.values()) {
            spacesPanel.add(new SpacePanel(space));
        }
        int cellIndex = spacesPanel.getComponentCount();
        while (cellIndex < cells) {
            spacesPanel.add(new JLabel());
            cellIndex++;
        }
        JLabel spacingInfoLabel = (JLabel) spacesPanel.getComponent(cells - 1);
        spacingInfoLabel.setHorizontalAlignment(JLabel.TRAILING);
        spacingInfoLabel.setText("<html>All values are in cm <i>(decimal)</i>  ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        templateNameTextField = new javax.swing.JTextField();
        formatTemplateTabbedPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        indentTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scaleTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maxShrinkingTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stretchLastStaffCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        landscapeCheckBox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        barsPerStaffTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortDescriptionTextArea = new javax.swing.JTextArea();
        marginAndSpacePanel = new javax.swing.JPanel();
        marginsPanel = new javax.swing.JPanel();
        topMarginTextField = new javax.swing.JTextField();
        topMarginTextField1 = new javax.swing.JTextField();
        topMarginTextField2 = new javax.swing.JTextField();
        topMarginTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        spacesPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tntFontsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        otherFontsPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        doneButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Template Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(templateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(655, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(templateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        formatTemplateTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Indentation of first note line:");

        indentTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        indentTextField.setText("0,0");

        jLabel3.setText("cm");

        jLabel4.setText("Scaling of notes:");

        scaleTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        jLabel5.setText("(default = 0.7)");

        jLabel6.setText("Maximum shrinking of notes:");

        maxShrinkingTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel7.setText("decimal");

        jLabel8.setText("decimal");

        jLabel9.setText("Stretch last staff:");

        jLabel10.setText("Landscape output:");

        jLabel11.setText("Number of bars per staff:");

        barsPerStaffTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        jLabel12.setText("(Leave empty if you want to controll this in the note body)");

        jLabel19.setText("Template Description:");

        shortDescriptionTextArea.setColumns(20);
        shortDescriptionTextArea.setRows(3);
        jScrollPane1.setViewportView(shortDescriptionTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(maxShrinkingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(indentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(scaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5))
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(landscapeCheckBox)
                                            .addComponent(stretchLastStaffCheckBox)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(barsPerStaffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12))))))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(indentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(scaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maxShrinkingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stretchLastStaffCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(landscapeCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(barsPerStaffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        formatTemplateTabbedPane.addTab("General", generalPanel);

        marginsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Margin"));

        topMarginTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        topMarginTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        topMarginTextField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        topMarginTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Top");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Right");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Bottom");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Left");

        jLabel17.setText("cm");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        jLabel18.setText("(decimal)");

        javax.swing.GroupLayout marginsPanelLayout = new javax.swing.GroupLayout(marginsPanel);
        marginsPanel.setLayout(marginsPanelLayout);
        marginsPanelLayout.setHorizontalGroup(
            marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(marginsPanelLayout.createSequentialGroup()
                        .addGroup(marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topMarginTextField3)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(27, 27, 27)
                        .addGroup(marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topMarginTextField1)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                    .addGroup(marginsPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topMarginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topMarginTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        marginsPanelLayout.setVerticalGroup(
            marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topMarginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(marginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topMarginTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topMarginTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 48, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(topMarginTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        spacesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Spaces"));
        spacesPanel.setLayout(new java.awt.GridLayout(12, 2, 5, 0));

        javax.swing.GroupLayout marginAndSpacePanelLayout = new javax.swing.GroupLayout(marginAndSpacePanel);
        marginAndSpacePanel.setLayout(marginAndSpacePanelLayout);
        marginAndSpacePanelLayout.setHorizontalGroup(
            marginAndSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginAndSpacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marginsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spacesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        marginAndSpacePanelLayout.setVerticalGroup(
            marginAndSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginAndSpacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(marginAndSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spacesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marginsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formatTemplateTabbedPane.addTab("Margins & Spaces", marginAndSpacePanel);

        tntFontsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tntFontsPanel.setLayout(new java.awt.GridLayout(10, 2, 5, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tntFontsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tntFontsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formatTemplateTabbedPane.addTab("Titles & Text Fonts", jPanel2);

        otherFontsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        otherFontsPanel.setLayout(new java.awt.GridLayout(10, 2, 5, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(otherFontsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(otherFontsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formatTemplateTabbedPane.addTab("Other Fonts", jPanel5);

        getContentPane().add(formatTemplateTabbedPane, java.awt.BorderLayout.CENTER);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Show PS-Fonts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton)
                    .addComponent(cancelButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        ok();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showPsFonts();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barsPerStaffTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JTabbedPane formatTemplateTabbedPane;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JTextField indentTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox landscapeCheckBox;
    private javax.swing.JPanel marginAndSpacePanel;
    private javax.swing.JPanel marginsPanel;
    private javax.swing.JTextField maxShrinkingTextField;
    private javax.swing.JPanel otherFontsPanel;
    private javax.swing.JTextField scaleTextField;
    private javax.swing.JTextArea shortDescriptionTextArea;
    private javax.swing.JPanel spacesPanel;
    private javax.swing.JCheckBox stretchLastStaffCheckBox;
    private javax.swing.JTextField templateNameTextField;
    private javax.swing.JPanel tntFontsPanel;
    private javax.swing.JTextField topMarginTextField;
    private javax.swing.JTextField topMarginTextField1;
    private javax.swing.JTextField topMarginTextField2;
    private javax.swing.JTextField topMarginTextField3;
    // End of variables declaration//GEN-END:variables

    private void showPsFonts() {
        new ShowPostScriptFontsAction(editor).actionPerformed(null);
    }

    @Override
    protected void accept() {
        updateTemplate();
    }

    private void updateTemplate() {
        if (template == null) {
            template = new FormatTemplate();
        }
        template.setName(templateNameTextField.getText());
        template.setShortDescription(shortDescriptionTextArea.getText());
        template.setIndent(getAsDouble(indentTextField));
        template.setScale(getAsDouble(scaleTextField));
        template.setMaxShrinking(getAsDouble(maxShrinkingTextField));
        template.setStretchLastStaff(stretchLastStaffCheckBox.isSelected());
        template.setLandscape(landscapeCheckBox.isSelected());
        template.setBarsPerStaff(getAsInteger(barsPerStaffTextField));
        set(template);
    }

    private Integer getAsInteger(JTextField field) {
        try {
            return Integer.valueOf(field.getText().replaceAll("\\D", ""));
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private Double getAsDouble(JTextField field) {
        try {
            return Double.valueOf(field.getText().replaceAll(",", "."));
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private void setAllFonts(PostScriptFont psFont) {
        fontPanels.stream().forEach((p) -> {
            p.setPsFont(psFont);
        });
    }

    private class SpacePanel extends JPanel {

        private final JTextField field;
        private final Dimension dimension = new Dimension(42, 27);

        public SpacePanel(FormatTemplate.Space space) {
            super(new BorderLayout());
            super.add(new JLabel(space.getName() + ":"), BorderLayout.CENTER);
            field = new JTextField();
            field.setSize(dimension);
            field.setPreferredSize(dimension);
            field.setMinimumSize(dimension);
            field.setMaximumSize(dimension);
            field.setHorizontalAlignment(JTextField.TRAILING);
            super.add(field, BorderLayout.EAST);
        }

        public void setValue(String value) {
            if (value != null && !value.isEmpty()) {
                try {
                    setValue(Double.valueOf(value.replaceAll(",", ".")));
                } catch (NumberFormatException e) {
                    Logger.getLogger(FormatTemplateDialog.class.getName()).log(Level.WARNING, "Could not convert value {0} to a Double.", value);
                }
            }
        }

        public void setValue(Double value) {
            field.setText(value.toString().replaceAll("\\.", ","));
        }

        public Double getValue() {
            if (field.getText() != null && !field.getText().isEmpty()) {
                try {
                    return Double.valueOf(field.getText().replaceAll(",", "."));
                } catch (NumberFormatException e) {
                    Logger.getLogger(FormatTemplateDialog.class.getName()).log(Level.WARNING, "Could not convert value {0} to a Double.", field.getText());
                }
            }
            return null;
        }
    }

    private class FontPanel extends JPanel {

        private JSpinner sizeSpinner;
        private final JComboBox postScriptFontComboBox;
        private final Dimension labelDimension = new Dimension(170, 27);
        private final Dimension sizeDimension = new Dimension(72, 27);
        private final int DEFAULT_SIZE = 14;

        public FontPanel(FormatTemplate.Font font) {
            super(new BorderLayout());
            JLabel label;
            if (font != null) {
                label = new JLabel(font.getName() + ":");
            } else {
                label = new JLabel("Select for All Fonts:");
            }
            label.setSize(labelDimension);
            label.setPreferredSize(labelDimension);
            label.setMinimumSize(labelDimension);
            label.setMaximumSize(labelDimension);
            super.add(label, BorderLayout.WEST);
            postScriptFontComboBox = new JComboBox(new DefaultComboBoxModel(PostScriptFont.values()));
            postScriptFontComboBox.setSelectedItem(PostScriptFont.DEFAULT_FONT);
            if (font == null) {
                postScriptFontComboBox.addItemListener((ItemEvent e) -> {
                    if (e.getSource() instanceof JComboBox) {
                        JComboBox box = (JComboBox) e.getSource();
                        PostScriptFont allFont = (PostScriptFont) box.getSelectedItem();
                        setAllFonts(allFont);
                    }
                });
            }
            super.add(postScriptFontComboBox, BorderLayout.CENTER);
            SpinnerNumberModel model = new SpinnerNumberModel(DEFAULT_SIZE, 4, 72, 1);
            if (font == null) {
                JLabel sizePlaceHolderLabel = new JLabel();
                sizePlaceHolderLabel.setSize(sizeDimension);
                sizePlaceHolderLabel.setPreferredSize(sizeDimension);
                sizePlaceHolderLabel.setMinimumSize(sizeDimension);
                sizePlaceHolderLabel.setMaximumSize(sizeDimension);
                super.add(sizePlaceHolderLabel, BorderLayout.EAST);
            } else {
                sizeSpinner = new JSpinner(model);
                sizeSpinner.setSize(sizeDimension);
                sizeSpinner.setPreferredSize(sizeDimension);
                sizeSpinner.setMinimumSize(sizeDimension);
                sizeSpinner.setMaximumSize(sizeDimension);
                super.add(sizeSpinner, BorderLayout.EAST);
            }
        }

        public void setPsFont(PostScriptFont psFont) {
            postScriptFontComboBox.setSelectedItem(psFont);
        }

        public void setFontValue(FormatTemplate.FontValue value) {
            postScriptFontComboBox.setSelectedItem(value.getPsFont());
            if (sizeSpinner != null) {
                sizeSpinner.setValue(value.getSize());
            }
        }

        public FormatTemplate.FontValue getFontValue() {
            PostScriptFont psFont = (PostScriptFont) postScriptFontComboBox.getSelectedItem();
            Integer size = DEFAULT_SIZE;
            if (sizeSpinner != null) {
                size = (Integer) sizeSpinner.getValue();
            }
            return new FormatTemplate.FontValue(psFont, size);
        }
    }
}
