package abc.music.editor.gui;

import abc.music.core.domain.Book;
import abc.music.editor.AbcMusicEditor;
import abc.music.editor.action.EditBookAction;
import abc.music.editor.gui.support.ListItemMouseListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hl
 */
public class BooksPanel extends AmeSidePanel {

    public BooksPanel(AbcMusicEditor editor) {
        super(editor);
    }

    @Override
    protected void init() {
        initComponents();
    }

    public void updateBooks() {
        if (editor.getProject() != null) {
            for (Book book : editor.getProject().getBooks()) {
                booksPanel.add(new BookItem(book));
            }
            booksPanel.repaint();
            booksPanel.revalidate();
        } else {
            booksPanel.removeAll();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        booksPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        booksPanel.setBackground(java.awt.Color.white);
        booksPanel.setLayout(new javax.swing.BoxLayout(booksPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(booksPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booksPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private class BookItem extends JLabel {

        public BookItem(Book book) {
            super.setText(book.getName());
            super.setIcon(new ImageIcon(getClass().getResource("/images/empty-icon.png")));
            super.addMouseListener(new ListItemMouseListener() {
                @Override
                protected void clickAction() {
                    new EditBookAction(editor, book).actionPerformed(null);
                }
            });
        }

    }

}
