package abc.music.editor.gui;

import abc.music.core.domain.Tune;
import abc.music.editor.AbcMusicEditor;
import java.awt.Component;


/**
 *
 * @author hl
 */
public class LatestTunesPane extends AmeSidePanel {

    public LatestTunesPane(AbcMusicEditor editor) {
        super(editor, editor.getProject());
    }

    @Override
    protected void init() {
        initComponents();
    }

    public void add(Tune tune) {
        if (tune.getTitles() != null && !tune.getTitles().isEmpty()) {
            TuneItem item = new TuneItem(editor, tune);
            for (Component c : containerPanel.getComponents()) {
                if (c instanceof TuneItem) {
                    if (((TuneItem) c).equals(item)) {
                        containerPanel.remove(c);
                    }
                }
            }
            containerPanel.add(item, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        containerPanel.setBackground(java.awt.Color.white);
        containerPanel.setLayout(new javax.swing.BoxLayout(containerPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(containerPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
