package abc.music.editor.gui;

import abc.music.editor.AbcMusicEditor;
import abc.music.editor.AmeConstants;
import javax.swing.JLabel;
import se.digitman.lightxml.DocumentToXmlNodeParser;
import se.digitman.lightxml.XmlNode;

/**
 *
 * @author hl
 */
public class LinksPanel extends AmeSidePanel {

    private XmlNode linksNode;

    public LinksPanel(AbcMusicEditor editor) {
        super(editor, editor.getProject());
    }

    @Override
    protected void init() {
        initComponents();
        linksNode = new DocumentToXmlNodeParser(getClass().getResourceAsStream("/links.xml")).parse();
        populateList();
    }

    private void populateList() {
        linksNode.getChildren("link-group").stream().forEach((node) -> {
            linkListPanel.add(new GroupLabel(node.getAttribute("title")));
            node.getChildren("link").stream().forEach((linkNode) -> {
                linkListPanel.add(new LinkItem(editor, linkNode));
            });
        });
        linkListPanel.repaint();
        linkListPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        linkListPanel = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        linkListPanel.setBackground(java.awt.Color.white);
        linkListPanel.setLayout(new javax.swing.BoxLayout(linkListPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(linkListPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel linkListPanel;
    // End of variables declaration//GEN-END:variables

    private class GroupLabel extends JLabel {

        public GroupLabel(String text) {
            super.setText("  " + text);
            super.setFont(AmeConstants.SMALL_TITLE_FONT);
            super.setForeground(AmeConstants.TITLE_COLOR);
        }

    }
}
