package abc.music.editor.gui;

import abc.music.core.domain.Tune;
import abc.music.editor.AbcMusicEditor;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Sequencer;
import nu.hex.abc.music.service.Service;
import nu.hex.abc.music.service.properties.AbcMusicProperties;

/**
 *
 * @author hl
 */
public class MidiPlayerPanel extends AmeSidePanel {

    private Sequencer sequencer;
    private File midiFile;
    private File tempFile;

    public MidiPlayerPanel(AbcMusicEditor editor) {
        super(editor);
    }

    @Override
    protected void init() {
        try {
            initComponents();
            sequencer = MidiSystem.getSequencer();
            sequencer.open();
        } catch (MidiUnavailableException ex) {
            Logger.getLogger(MidiPlayerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setSequence() {
        InputStream midiSource = null;
        try {
            Tune tune = editor.getTuneEditor().getTune();
            Service service = new Service(editor.getProject());
            tempFile = new File(service.getPropertyService().getProperty(AbcMusicProperties.MIDI_FOLDER) + "/temp-" + tune.getName() + ".mid");
            midiFile = service.getIoService().createMidiFile(editor.getTuneEditor().getTune(), tempFile);
            midiSource = new FileInputStream(midiFile);
            sequencer.setSequence(midiSource);
        } catch (InvalidMidiDataException | IOException ex) {
            Logger.getLogger(MidiPlayerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (midiSource != null) {
                    midiSource.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(MidiPlayerPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (midiFile != null) {
                midiFile.delete();
            }
            if (tempFile != null) {
                tempFile.delete();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();

        setOpaque(false);

        playButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        playButton.setText(">");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        pauseButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pauseButton.setText("||");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        stopButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        stopButton.setText("·");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton)
                    .addComponent(pauseButton)
                    .addComponent(stopButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        setSequence();
        sequencer.start();
    }//GEN-LAST:event_playButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        sequencer.stop();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        sequencer.stop();
    }//GEN-LAST:event_stopButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
