package abc.music.editor.gui;

import abc.music.core.domain.Tune;
import abc.music.editor.AbcMusicEditor;
import abc.music.editor.action.UpdateSvgFileAction;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.io.File;
import nu.hex.abc.music.service.properties.AbcMusicProperties;
import nu.hex.abc.music.service.properties.PropertyService;
import org.apache.batik.swing.JSVGCanvas;

/**
 *
 * @author hl
 */
public class SvgViewPanel extends JPanel {

    private JSVGCanvas canvas;
    private final File file;
    private Tune tune;

    public SvgViewPanel(AbcMusicEditor editor, Tune tune) {
        initComponents();
        init();
        this.tune = tune;
        String svgFolder = PropertyService.getProperties().getProperty(AbcMusicProperties.PROJECT_SVG_FOLDER);
        String tuneFileName = tune.getName().replaceAll(" ", "_");
        UpdateSvgFileAction action = new UpdateSvgFileAction(editor, tune);
        action.actionPerformed(null);
        file = action.get();
    }

    private void init() {
        canvas = new JSVGCanvas();
        svgCanvasPanel.add(canvas, BorderLayout.CENTER);
    }

    public Tune getTune() {
        return tune;
    }

    public void updateFile() {
        canvas.setURI(file.toURI().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        svgCanvasPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        svgCanvasPanel.setBackground(java.awt.Color.white);
        svgCanvasPanel.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(svgCanvasPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel svgCanvasPanel;
    // End of variables declaration//GEN-END:variables
}
